/**
 * Domain model for a partner profile.
 *
 * Spring Boot analogy: this is the aggregate root. Everything the app knows
 * about one partner (who they are, where they live, what they're into and how
 * deeply, which prompts they liked or hid, which prompts were shown recently,
 * and the AI-written questions made for them) lives in ONE object, which maps
 * to ONE MongoDB document.
 */

/** +1 = "good question, show more like this"; -1 = "bad question, hide it". */
export type Score = 1 | -1;

export interface QuestionFeedback {
  questionId: string;
  score: Score;
  ratedAt: Date;
}

/**
 * Answers to the per-interest follow-up questions, keyed by interest id then
 * follow-up id. A multi-choice answer is a string array; everything else a string.
 *
 *   { sports: { sport: ['Football'], team: 'Vikings' }, music: { genre: ['Jazz', 'Folk'] } }
 */
export type InterestDetails = Record<string, Record<string, string | string[]>>;

/**
 * Where your person lives, as a place name. We deliberately store no
 * coordinates: the app may use the device's location to look the city up, but
 * only the name reaches the server. It drives local questions ("anywhere in
 * Minneapolis you've been meaning to try?") and anchors the AI research.
 */
export interface ProfileLocation {
  city: string;
  region?: string;
  country?: string;
}

/** A question written by the AI engine for this profile specifically. */
export interface GeneratedQuestion {
  /** Prefixed `ai-` so it can never collide with a curated id. */
  id: string;
  text: string;
  /** Interest ids it relates to, or ['general']. */
  tags: string[];
  /** The model's one-line reason, kept for debugging and future UI. */
  basis: string;
  createdAt: Date;
}

export interface GeneratedSet {
  questions: GeneratedQuestion[];
  generatedAt: Date | null;
  /** Hash of the profile inputs the set was built from; a change marks it stale. */
  basis: string;
}

export const EMPTY_GENERATED: GeneratedSet = { questions: [], generatedAt: null, basis: '' };

/**
 * Something your person said, written down after a question. The other half
 * of the app: asking is half, remembering is the rest. Also the best input the
 * AI engine gets.
 */
export interface Memory {
  id: string;
  questionId?: string;
  /** The question text at the time, so the memory still reads if the bank changes. */
  questionText?: string;
  text: string;
  createdAt: Date;
}

/** A birthday, an anniversary, the kids' recital. Month and day only; it recurs yearly. */
export interface ImportantDate {
  id: string;
  label: string;
  month: number;
  day: number;
}

export interface PartnerProfile {
  /** UUID generated by the API. Acts as the only credential for now (see docs/ROADMAP.md). */
  id: string;
  /** What you call your person. Shown as "Ask Sam" above each prompt. */
  name: string;
  /** Interest tag ids from `questions/interests.ts`. */
  interests: string[];
  /** Follow-up answers for the selected interests. See InterestDetails. */
  interestDetails: InterestDetails;
  location?: ProfileLocation;
  /** Free text: "What's going on in their world lately?" */
  currentFocus?: string;
  /** Free text: anything else worth remembering. */
  notes?: string;
  /** One entry per rated question. Latest rating wins (we upsert). */
  feedback: QuestionFeedback[];
  /** Question ids in the order they were shown, oldest first, capped. */
  recentlyShown: string[];
  /** AI-written questions for this profile. Empty when the AI engine is off. */
  generated: GeneratedSet;
  memories: Memory[];
  dates: ImportantDate[];
  /** When interests or follow-up answers last changed; drives the "still true?" nudge. */
  detailsUpdatedAt: Date;
  createdAt: Date;
  updatedAt: Date;
}

/** How many previously shown question ids we remember, to avoid repeats. */
export const RECENTLY_SHOWN_LIMIT = 30;

/** The shape we send to clients: internal bookkeeping stays server-side. */
export interface ProfileResponse {
  id: string;
  name: string;
  interests: string[];
  interestDetails: InterestDetails;
  location?: ProfileLocation;
  currentFocus?: string;
  notes?: string;
  dates: ImportantDate[];
  memoryCount: number;
  detailsUpdatedAt: Date;
  createdAt: Date;
  updatedAt: Date;
  /** How many questions this person has hidden. */
  hiddenCount: number;
  /** How many AI-written questions are currently in this profile's deck. */
  aiQuestionCount: number;
  /** When the AI deck was last refreshed, if ever. */
  aiGeneratedAt: Date | null;
}

export function toProfileResponse(profile: PartnerProfile): ProfileResponse {
  return {
    id: profile.id,
    name: profile.name,
    interests: profile.interests,
    interestDetails: profile.interestDetails,
    location: profile.location,
    currentFocus: profile.currentFocus,
    notes: profile.notes,
    dates: profile.dates,
    memoryCount: profile.memories.length,
    detailsUpdatedAt: profile.detailsUpdatedAt,
    createdAt: profile.createdAt,
    updatedAt: profile.updatedAt,
    hiddenCount: profile.feedback.filter((f) => f.score === -1).length,
    aiQuestionCount: profile.generated.questions.length,
    aiGeneratedAt: profile.generated.generatedAt,
  };
}
