/**
 * Domain model for a partner profile.
 *
 * Spring Boot analogy: this is the aggregate root. Everything the app knows
 * about one partner (who they are, what they're into and how deeply, which
 * prompts they liked or hid, which prompts were shown recently) lives in ONE
 * object, which maps to ONE MongoDB document. That is the big mindset shift
 * from relational modelling: instead of profile + interest + detail + feedback
 * tables joined by foreign keys, the child collections are embedded inside
 * the parent document.
 */

/** +1 = "good question, show more like this"; -1 = "bad question, hide it". */
export type Score = 1 | -1;

export interface QuestionFeedback {
  questionId: string;
  score: Score;
  ratedAt: Date;
}

/**
 * Answers to the per-interest follow-up questions, keyed by interest id then
 * follow-up id. A multi-choice answer is a string array; everything else a string.
 *
 *   { sports: { sport: ['Football'], team: 'Vikings' }, music: { genre: ['Jazz', 'Folk'] } }
 *
 * This is where a document database earns its keep: the shape varies per
 * profile and per interest, and we never query across it. In SQL this would be
 * an EAV table or a JSONB column; in Mongo it is just a nested object.
 */
export type InterestDetails = Record<string, Record<string, string | string[]>>;

export interface PartnerProfile {
  /** UUID generated by the API. Acts as the only credential for now (see docs/ROADMAP.md). */
  id: string;
  /** What you call your person. Shown as "Ask Sam" above each prompt. */
  name: string;
  /** Interest tag ids from `questions/interests.ts`. */
  interests: string[];
  /** Follow-up answers for the selected interests. See InterestDetails. */
  interestDetails: InterestDetails;
  /** Free text: "What's going on in their world lately?" */
  currentFocus?: string;
  /** Free text: anything else worth remembering. */
  notes?: string;
  /** One entry per rated question. Latest rating wins (we upsert). */
  feedback: QuestionFeedback[];
  /** Question ids in the order they were shown, oldest first, capped. */
  recentlyShown: string[];
  createdAt: Date;
  updatedAt: Date;
}

/** How many previously shown question ids we remember, to avoid repeats. */
export const RECENTLY_SHOWN_LIMIT = 30;

/** The shape we send to clients: internal bookkeeping stays server-side. */
export interface ProfileResponse {
  id: string;
  name: string;
  interests: string[];
  interestDetails: InterestDetails;
  currentFocus?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
  /** How many questions this person has hidden. Useful for a settings screen later. */
  hiddenCount: number;
}

export function toProfileResponse(profile: PartnerProfile): ProfileResponse {
  return {
    id: profile.id,
    name: profile.name,
    interests: profile.interests,
    interestDetails: profile.interestDetails,
    currentFocus: profile.currentFocus,
    notes: profile.notes,
    createdAt: profile.createdAt,
    updatedAt: profile.updatedAt,
    hiddenCount: profile.feedback.filter((f) => f.score === -1).length,
  };
}
